/*
 * Copyright 2015 Nils Ryter.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ch.arkeine.markupextractor.userinterface;

import ch.arkeine.markupextractor.extractor.Command;

/**
 *
 * @author Nils Ryter
 */
public class CommandEditorConsole extends javax.swing.JPanel {

    /**
     * Creates new form CommandEditorConsole
     */
    public CommandEditorConsole() {
        initComponents();
    }

    public String getText() {
        return txtCommand.getText();
    }

    public void setText(String t) {
        txtCommand.setText(t);
    }

    public void loadCommand(Command[] tabCommand) {
        StringBuilder s = new StringBuilder();

        for (Command c : tabCommand) {
            s.append(c.getName().toString());
            s.append("\t");
            s.append(c.getParameter1());
            s.append("\t");
            s.append(c.getParameter2());
        }

        txtCommand.setText(s.toString());
    }

    public Command[] saveCommand() {
        StringBuilder s = new StringBuilder();

        if (compilationCommand()) {
            String[] tmp = txtCommand.getText().split("\n");
            Command[] tabCmd = new Command[tmp.length];

            int i = 0;
            for (String line : tmp) {
                String[] cmd = line.split("\t");
                tabCmd[i] = new Command();
                tabCmd[i].setName(Command.CommandName.valueOf(cmd[0]));
                tabCmd[i].setParameter1(cmd[1]);
                tabCmd[i].setParameter2(cmd[2]);
            }
            return tabCmd;
        }
        return new Command[0];
    }

    private boolean compilationCommand() {
        String[] tmp = txtCommand.getText().split("\n");

        for (String line : tmp) {
            String[] cmd = line.split("\t");

            if (cmd.length != 3) {
                int i = txtCommand.getText().indexOf(line);
                txtCommand.setSelectionStart(i);
                txtCommand.setSelectionEnd(i + line.length());
                return false;
            }

            try {
                Command.CommandName.valueOf(cmd[0]);
            } catch (IllegalArgumentException e) {
                int i = txtCommand.getText().indexOf(line);
                txtCommand.setSelectionStart(i);
                txtCommand.setSelectionEnd(i + line.length());
                return false;
            }
        }

        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtCommand = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();

        txtCommand.setColumns(20);
        txtCommand.setRows(5);
        jScrollPane1.setViewportView(txtCommand);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea txtCommand;
    // End of variables declaration//GEN-END:variables
}
