/*
 * Copyright 2015 Nils Ryter.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ch.arkeine.markupextractor.userinterface.wizard;

import ch.arkeine.markupextractor.tool.ToolUrls;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author Nils Ryter
 */
public class DataSelector extends javax.swing.JPanel {
    
    /**
     * Creates new form DataSelector
     */
    public DataSelector() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panOccurence = new javax.swing.JPanel();
        titleOccurenceNumber = new javax.swing.JLabel();
        titleOccurenceText = new javax.swing.JLabel();
        txtOccurenceText = new javax.swing.JTextField();
        spOccurenceNumber = new javax.swing.JSpinner();
        btLoadFromSelection = new javax.swing.JButton();
        btSearch = new javax.swing.JButton();
        panContent = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtContent = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();
        jPanel1 = new javax.swing.JPanel();
        txtUrl = new javax.swing.JTextField();
        btLoadUrl = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ch/arkeine/markupextractor/internationalization"); // NOI18N
        panOccurence.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("DataSelector.panOccurence.border.title"))); // NOI18N

        titleOccurenceNumber.setText(bundle.getString("DataSelector.titleOccurenceNumber.text")); // NOI18N

        titleOccurenceText.setText(bundle.getString("DataSelector.titleOccurenceText.text")); // NOI18N

        txtOccurenceText.setText(bundle.getString("DataSelector.txtOccurenceText.text")); // NOI18N

        spOccurenceNumber.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        btLoadFromSelection.setText(bundle.getString("DataSelector.btLoadFromSelection.text")); // NOI18N
        btLoadFromSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadFromSelectionActionPerformed(evt);
            }
        });

        btSearch.setText(bundle.getString("DataSelector.btSearch.text")); // NOI18N
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panOccurenceLayout = new javax.swing.GroupLayout(panOccurence);
        panOccurence.setLayout(panOccurenceLayout);
        panOccurenceLayout.setHorizontalGroup(
            panOccurenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOccurenceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panOccurenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOccurenceText)
                    .addComponent(spOccurenceNumber)
                    .addComponent(btLoadFromSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panOccurenceLayout.createSequentialGroup()
                        .addGroup(panOccurenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleOccurenceText)
                            .addComponent(titleOccurenceNumber))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panOccurenceLayout.setVerticalGroup(
            panOccurenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOccurenceLayout.createSequentialGroup()
                .addComponent(titleOccurenceText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOccurenceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleOccurenceNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spOccurenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLoadFromSelection)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        panContent.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("DataSelector.panContent.border.title"))); // NOI18N

        txtContent.setColumns(20);
        txtContent.setRows(5);
        txtContent.setSyntaxEditingStyle(bundle.getString("DataSelector.txtContent.syntaxEditingStyle")); // NOI18N
        jScrollPane2.setViewportView(txtContent);

        javax.swing.GroupLayout panContentLayout = new javax.swing.GroupLayout(panContent);
        panContent.setLayout(panContentLayout);
        panContentLayout.setHorizontalGroup(
            panContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        panContentLayout.setVerticalGroup(
            panContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("DataSelector.jPanel1.border.title"))); // NOI18N

        txtUrl.setText(bundle.getString("DataSelector.txtUrl.text")); // NOI18N

        btLoadUrl.setText(bundle.getString("DataSelector.btLoadUrl.text")); // NOI18N
        btLoadUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadUrlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLoadUrl)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btLoadUrl))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panOccurence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panOccurence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btLoadUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadUrlActionPerformed
        try {
            txtContent.setText(ToolUrls.loadURL(txtUrl.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(DataSelector.class.getName()).log(Level.SEVERE,
                    null, ex);
        }
    }//GEN-LAST:event_btLoadUrlActionPerformed

    private void btLoadFromSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadFromSelectionActionPerformed
        String s = txtContent.getSelectedText();
        String c = txtContent.getText().substring(0,
                txtContent.getSelectionEnd());

        txtOccurenceText.setText(s);
        spOccurenceNumber.setValue(StringUtils.countMatches(c, s));
    }//GEN-LAST:event_btLoadFromSelectionActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        String s = txtOccurenceText.getText();
        String c = txtContent.getText();
        int numberOcc = (int)spOccurenceNumber.getValue();
        
        int begin = 0;
        int currentNum = 0;
        
        while(currentNum != numberOcc)
        {
            begin = c.indexOf(s, begin)+s.length();
            currentNum++;
        }
        
        txtContent.setSelectionStart(begin-s.length());
        txtContent.setSelectionEnd(begin);
    }//GEN-LAST:event_btSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLoadFromSelection;
    private javax.swing.JButton btLoadUrl;
    private javax.swing.JButton btSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panContent;
    private javax.swing.JPanel panOccurence;
    private javax.swing.JSpinner spOccurenceNumber;
    private javax.swing.JLabel titleOccurenceNumber;
    private javax.swing.JLabel titleOccurenceText;
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea txtContent;
    private javax.swing.JTextField txtOccurenceText;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables

    public String getContent() {
        return txtContent.getText();
    }

    public int getOccurenceNumber() {
        return (int) spOccurenceNumber.getValue();
    }

    public String getOccurenceText() {
        return txtOccurenceText.getText();
    }
}
