/*
 * Copyright 2015 Nils Ryter.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ch.arkeine.markupextractor.userinterface.wizard;

import ch.arkeine.markupextractor.tool.ToolMarkups;
import ch.arkeine.markupextractor.tool.ToolMessages;
import ch.arkeine.markupextractor.tool.ToolUrls;
import ch.arkeine.markupextractor.userinterface.ScriptEditorMenu;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author Nils Ryter
 */
public class DataSelector extends javax.swing.JPanel {

    /**
     * Creates new form DataSelector
     */
    public DataSelector() {
        initComponents();
    }

    public String getContent() {
        return textAreaDocument.getText();
    }

    public int getOccurenceNumber() {
        return (int) spinnerOccurence.getValue();
    }

    public String getOccurenceText() {
        return textFieldOccurence.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOccurence = new javax.swing.JPanel();
        labelOccurenceNumber = new javax.swing.JLabel();
        labelOccurenceText = new javax.swing.JLabel();
        textFieldOccurence = new javax.swing.JTextField();
        spinnerOccurence = new javax.swing.JSpinner();
        buttonLoadFromSelection = new javax.swing.JButton();
        buttonSearch = new javax.swing.JButton();
        panContent = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDocument = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();
        jPanel1 = new javax.swing.JPanel();
        textFieldUrl = new javax.swing.JTextField();
        buttonLoadUrl = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ch/arkeine/markupextractor/internationalization"); // NOI18N
        panelOccurence.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("DataSelector.panelOccurence.border.title"))); // NOI18N

        labelOccurenceNumber.setText(bundle.getString("DataSelector.labelOccurenceNumber.text")); // NOI18N

        labelOccurenceText.setText(bundle.getString("DataSelector.labelOccurenceText.text")); // NOI18N

        textFieldOccurence.setText(bundle.getString("DataSelector.textFieldOccurence.text")); // NOI18N

        spinnerOccurence.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        buttonLoadFromSelection.setText(bundle.getString("DataSelector.buttonLoadFromSelection.text")); // NOI18N
        buttonLoadFromSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoadFromSelectionActionPerformed(evt);
            }
        });

        buttonSearch.setText(bundle.getString("DataSelector.buttonSearch.text")); // NOI18N
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOccurenceLayout = new javax.swing.GroupLayout(panelOccurence);
        panelOccurence.setLayout(panelOccurenceLayout);
        panelOccurenceLayout.setHorizontalGroup(
            panelOccurenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOccurenceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOccurenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldOccurence)
                    .addComponent(spinnerOccurence)
                    .addComponent(buttonLoadFromSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelOccurenceLayout.createSequentialGroup()
                        .addGroup(panelOccurenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelOccurenceText)
                            .addComponent(labelOccurenceNumber))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelOccurenceLayout.setVerticalGroup(
            panelOccurenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOccurenceLayout.createSequentialGroup()
                .addComponent(labelOccurenceText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldOccurence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelOccurenceNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerOccurence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLoadFromSelection)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        panContent.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("DataSelector.panContent.border.title"))); // NOI18N

        textAreaDocument.setColumns(20);
        textAreaDocument.setRows(5);
        textAreaDocument.setSyntaxEditingStyle(bundle.getString("DataSelector.textAreaDocument.syntaxEditingStyle")); // NOI18N
        jScrollPane2.setViewportView(textAreaDocument);

        javax.swing.GroupLayout panContentLayout = new javax.swing.GroupLayout(panContent);
        panContent.setLayout(panContentLayout);
        panContentLayout.setHorizontalGroup(
            panContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        panContentLayout.setVerticalGroup(
            panContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("DataSelector.jPanel1.border.title"))); // NOI18N

        textFieldUrl.setText(bundle.getString("DataSelector.textFieldUrl.text")); // NOI18N

        buttonLoadUrl.setText(bundle.getString("DataSelector.buttonLoadUrl.text")); // NOI18N
        buttonLoadUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoadUrlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(textFieldUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonLoadUrl)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(textFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(buttonLoadUrl))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelOccurence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOccurence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoadUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoadUrlActionPerformed
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle(
                "ch/arkeine/markupextractor/internationalization"); // NOI18N
        String summary = bundle.getString(".message.errorSummary");
        String title = bundle.getString(".message.errorTitle");

        try {
            textAreaDocument.setText(ToolUrls.loadURL(textFieldUrl.getText()));
        } catch (Exception ex) {
            ToolMessages.showException(this, summary, title, ex);
            Logger.getLogger(ScriptEditorMenu.class.getName()).log(
                    Level.WARNING, null, ex);
        }
    }//GEN-LAST:event_buttonLoadUrlActionPerformed

    private void buttonLoadFromSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoadFromSelectionActionPerformed
        String s = textAreaDocument.getSelectedText();
        if (s != null) {
            String c = textAreaDocument.getText().substring(0,
                    textAreaDocument.getSelectionEnd());

            textFieldOccurence.setText(s);
            spinnerOccurence.setValue(StringUtils.countMatches(c, s));
        }
    }//GEN-LAST:event_buttonLoadFromSelectionActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        String s = textFieldOccurence.getText();
        String c = textAreaDocument.getText();
        int numberOcc = (int) spinnerOccurence.getValue();

        int begin = ToolMarkups.searchOccurenceIndex(c, s, numberOcc);

        textAreaDocument.setSelectionStart(begin - s.length());
        textAreaDocument.setSelectionEnd(begin);
        textAreaDocument.requestFocus();
    }//GEN-LAST:event_buttonSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLoadFromSelection;
    private javax.swing.JButton buttonLoadUrl;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelOccurenceNumber;
    private javax.swing.JLabel labelOccurenceText;
    private javax.swing.JPanel panContent;
    private javax.swing.JPanel panelOccurence;
    private javax.swing.JSpinner spinnerOccurence;
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea textAreaDocument;
    private javax.swing.JTextField textFieldOccurence;
    private javax.swing.JTextField textFieldUrl;
    // End of variables declaration//GEN-END:variables
}
