/*
 * Copyright 2015 nils.ryter.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ch.arkeine.markupextractor.userinterface.extractor;

import ch.arkeine.markupextractor.extractor.Command;
import ch.arkeine.markupextractor.extractor.Extractor;
import ch.arkeine.markupextractor.tool.ToolFiles;
import ch.arkeine.markupextractor.tool.ToolMessages;
import ch.arkeine.markupextractor.tool.ToolUrls;
import ch.arkeine.markupextractor.userinterface.ScriptEditorMenu;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author nils.ryter
 */
public class SaveExtractedData extends javax.swing.JPanel {

    private Extractor extractor;
    
    public SaveExtractedData() {
        initComponents();
        extractor = new Extractor(new Command[0], new String[0], false);
    }
    
    public void setDataSource(Extractor e){
        extractor = e;
    }

    private void writeUrlsFile(String[] urls) {
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle(
                "ch/arkeine/markupextractor/internationalization"); // NOI18N
        
        String extension = bundle.getString(".constant.urlFile.extension");
        String description = bundle.getString(".constant.urlFile.description");
        String summary = bundle.getString(".message.errorSummary");
        String title = bundle.getString(".message.errorTitle");

        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(ToolFiles.getFilter(extension, description));
        fc.showSaveDialog(this);

        if (fc.getSelectedFile() != null) {

            try {
                ToolFiles.writeStringToFile(ToolUrls.urlsToString(urls, "\n"),
                        fc.getSelectedFile().getAbsolutePath(),extension);
            } catch (IOException ex) {
                ToolMessages.showException(this, summary, title, ex);
                Logger.getLogger(ScriptEditorMenu.class.getName()).log(
                        Level.WARNING, null, ex);
            }
        }
    }
    
    private void writeDataToFile(){
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle(
            "ch/arkeine/markupextractor/internationalization"); // NOI18N
        String extension = bundle.getString(".constant.urlFile.extension");
        String description = bundle.getString(".constant.urlFile.description");
        String summary = bundle.getString(".message.errorSummary");
        String title = bundle.getString(".message.errorTitle");

        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(ToolFiles.getFilter(extension, description));
        fc.showSaveDialog(this);

        String separator = JOptionPane.showInputDialog(this,
            bundle.getString("SummaryMenu.input.separator"));

        if (separator != null && !separator.isEmpty() && fc.getSelectedFile() != null) {

            try {
                ToolFiles.writeStringToFile(
                    extractor.getExtractedToCSV(separator),
                    fc.getSelectedFile().getAbsolutePath(),extension);
            } catch (IOException ex) {
                ToolMessages.showException(this, summary, title, ex);
                Logger.getLogger(ScriptEditorMenu.class.getName()).log(
                    Level.WARNING, null, ex);
            }

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btSaveData = new javax.swing.JButton();
        titleSaveData = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        titleSaveAllUrl = new javax.swing.JLabel();
        btSaveAllUrl = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        titleSaveUrlsSuccess = new javax.swing.JLabel();
        btSaveUrlSuccess = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        titleSaveUrlError = new javax.swing.JLabel();
        btSaveUrlError = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(2, 2));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ch/arkeine/markupextractor/internationalization"); // NOI18N
        btSaveData.setText(bundle.getString("SaveExtractedData.btSaveData.text")); // NOI18N
        btSaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveDataActionPerformed(evt);
            }
        });

        titleSaveData.setText(bundle.getString("SaveExtractedData.titleSaveData.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSaveData)
                    .addComponent(titleSaveData))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleSaveData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSaveData)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        add(jPanel2);

        titleSaveAllUrl.setText(bundle.getString("SaveExtractedData.titleSaveAllUrl.text")); // NOI18N

        btSaveAllUrl.setText(bundle.getString("SaveExtractedData.btSaveAllUrl.text")); // NOI18N
        btSaveAllUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveAllUrlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleSaveAllUrl)
                    .addComponent(btSaveAllUrl))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleSaveAllUrl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSaveAllUrl)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        add(jPanel3);

        titleSaveUrlsSuccess.setText(bundle.getString("SaveExtractedData.titleSaveUrlsSuccess.text")); // NOI18N

        btSaveUrlSuccess.setText(bundle.getString("SaveExtractedData.btSaveUrlSuccess.text")); // NOI18N
        btSaveUrlSuccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveUrlSuccessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleSaveUrlsSuccess)
                    .addComponent(btSaveUrlSuccess))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleSaveUrlsSuccess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSaveUrlSuccess)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        add(jPanel6);

        titleSaveUrlError.setText(bundle.getString("SaveExtractedData.titleSaveUrlError.text")); // NOI18N

        btSaveUrlError.setText(bundle.getString("SaveExtractedData.btSaveUrlError.text")); // NOI18N
        btSaveUrlError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveUrlErrorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleSaveUrlError)
                    .addComponent(btSaveUrlError))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleSaveUrlError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSaveUrlError)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveDataActionPerformed
        writeDataToFile();
    }//GEN-LAST:event_btSaveDataActionPerformed

    private void btSaveAllUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveAllUrlActionPerformed
        writeUrlsFile(extractor.getDoc());
    }//GEN-LAST:event_btSaveAllUrlActionPerformed

    private void btSaveUrlErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveUrlErrorActionPerformed
        writeUrlsFile(extractor.getNoExtractedDoc());
    }//GEN-LAST:event_btSaveUrlErrorActionPerformed

    private void btSaveUrlSuccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveUrlSuccessActionPerformed
        writeUrlsFile(extractor.getExtractedDoc());
    }//GEN-LAST:event_btSaveUrlSuccessActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSaveAllUrl;
    private javax.swing.JButton btSaveData;
    private javax.swing.JButton btSaveUrlError;
    private javax.swing.JButton btSaveUrlSuccess;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel titleSaveAllUrl;
    private javax.swing.JLabel titleSaveData;
    private javax.swing.JLabel titleSaveUrlError;
    private javax.swing.JLabel titleSaveUrlsSuccess;
    // End of variables declaration//GEN-END:variables
}
